# Copyright 2025 Google LLC
#
# Use of this source code is governed by an MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT.

require_relative "../config/environment"
require "sinatra/activerecord/rake"

desc "Sample showing how to use Batch DML with the Spanner ActiveRecord provider."
task :run do
  Dir.chdir("..") { sh "bundle exec rake run[batch-dml]" }
end
