# Copyright 2025 Google LLC
#
# Use of this source code is governed by an MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT.

class CreateAutoGeneratedPrimaryKey < ActiveRecord::Migration[7.0]
  def change
    connection.start_batch_ddl
    create_table :table_with_identity do |t|
      t.string :name, null: false
      t.integer :age, null: false
    end
    connection.run_batch
  end
end
