name: acceptance tests on production

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
jobs:
  check-env:
    outputs:
      has-key: ${{ steps.project-id.outputs.defined }}
    runs-on: ubuntu-latest
    steps:
    - id: project-id
      env:
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      if: "${{ env.GCP_PROJECT_ID != '' }}"
      run: echo "::set-output name=defined::true"

  test:
    needs: [check-env]
    if: needs.check-env.outputs.has-key == 'true'
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        ruby: [3.3]
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby
    # (see https://github.com/ruby/setup-ruby#versioning):
      uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
      with:
        bundler-cache: true
        ruby-version: ${{ matrix.ruby }}
    - name: Authenticate Google Cloud
      uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    - name: Setup GCloud
      uses: google-github-actions/setup-gcloud@aa5489c8933f4cc7a4f7d45035b3b1440c9c10db # v3.0.1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
    - name: Install dependencies
      run: bundle install
    - name: Run acceptance tests on production
      run: bundle exec rake acceptance\[,,,"exclude cases/migration"\] TESTOPTS="-v"
      env:
        SPANNER_TEST_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
        SPANNER_TEST_INSTANCE: ruby-activerecord-test
