name: ci

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        ruby: ["3.2", "3.3", "3.4", "4.0"]
        ar: ["~> 7.0.0", "~> 7.1.0", "~> 7.2.0", "~> 8.0.0", "~> 8.1.0"]
        # Exclude combinations that are not supported.
        exclude:
          - ruby: "3.4"
            ar: "~> 7.0.0"
          - ruby: "3.4"
            ar: "~> 7.1.0"
          - ruby: "3.4"
            ar: "~> 7.2.0"
          - ruby: "4.0"
            ar: "~> 7.0.0"
          - ruby: "4.0"
            ar: "~> 7.1.0"
          - ruby: "4.0"
            ar: "~> 7.2.0"
    env:
      AR_VERSION: ${{ matrix.ar }}
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby
    # (see https://github.com/ruby/setup-ruby#versioning):
      uses: ruby/setup-ruby@8e41b362d2589a22a44c1cfa214b3c83052c195b # v1.318.0
      with:
        bundler-cache: false
        ruby-version: ${{ matrix.ruby }}
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rake test --trace TESTOPTS="-v"
