name: nightly acceptance tests on production

permissions:
  contents: read

on:
  schedule:
    # 02:00 UTC
    - cron:  '0 2 * * *'
jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        ruby: [3.3]
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby
    # (see https://github.com/ruby/setup-ruby#versioning):
      uses: ruby/setup-ruby@a30dfa457ad68707b8b910ac3a244714b61c0626 # v1.320.0
      with:
        bundler-cache: true
        ruby-version: ${{ matrix.ruby }}
    - name: Authenticate Google Cloud
      uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    - name: Setup GCloud
      uses: google-github-actions/setup-gcloud@aa5489c8933f4cc7a4f7d45035b3b1440c9c10db # v3.0.1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
    - name: Install dependencies
      run: bundle install
    - name: Run acceptance tests on production
      run: bundle exec rake acceptance\[,,,"exclude cases/migration"\]
      env:
        SPANNER_TEST_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
        SPANNER_TEST_INSTANCE: ruby-activerecord-test
