on:
  schedule:
    # 06:00 UTC
    - cron:  '0 6 * * *'
  workflow_dispatch:
name: nightly acceptance tests on emulator
jobs:
  test:
    runs-on: ubuntu-latest

    services:
      emulator:
        image: gcr.io/cloud-spanner-emulator/emulator:latest
        ports:
          - 9010:9010
          - 9020:9020

    strategy:
      max-parallel: 4
      matrix:
        ruby: ["3.1", "3.2", "3.3"]
        ar: ["~> 6.1.0", "~> 7.0.0", "~> 7.1.0", "~> 7.2.0"]
    env:
      AR_VERSION: ${{ matrix.ar }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        # Disable caching as we are overriding the ActiveRecord below.
        bundler-cache: false
        ruby-version: ${{ matrix.ruby }}
    - name: Install dependencies
      run: bundle install
    - name: Run acceptance tests on emulator
      run: bundle exec rake acceptance
      env:
        SPANNER_EMULATOR_HOST: localhost:9010
        SPANNER_TEST_PROJECT: test-project
        SPANNER_TEST_INSTANCE: test-instance
