on:
  schedule:
    # 06:00 UTC
    - cron:  '0 6 * * *'
name: nightly acceptance tests on emulator
jobs:
  test:
    runs-on: ubuntu-latest

    services:
      emulator:
        image: gcr.io/cloud-spanner-emulator/emulator:latest
        ports:
          - 9010:9010
          - 9020:9020

    strategy:
      max-parallel: 4
      matrix:
        # Run acceptance tests all supported combinations of Ruby and ActiveRecord.
        ruby: [2.5, 2.6, 2.7, 3.0]
        ar: [6.0.0, 6.0.1, 6.0.2.2, 6.0.3.7, 6.0.4, 6.1.0, 6.1.1, 6.1.2.1, 6.1.3.2, 6.1.4, 7.0.2.4]
        # Exclude combinations that are not supported.
        exclude:
          - ruby: 3.0
            ar: 6.0.0
          - ruby: 3.0
            ar: 6.0.1
          - ruby: 3.0
            ar: 6.0.2.2
          - ruby: 3.0
            ar: 6.0.3.7
          - ruby: 3.0
            ar: 6.0.4
          - ruby: 2.5
            ar: 7.0.2.4
          - ruby: 2.6
            ar: 7.0.2.4
    env:
      AR_VERSION: ${{ matrix.ar }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        # Disable caching as we are overriding the ActiveRecord below.
        bundler-cache: false
        ruby-version: ${{ matrix.ruby }}
    - name: Install dependencies
      run: bundle install
    - name: Run acceptance tests on emulator
      run: bundle exec rake acceptance
      env:
        SPANNER_EMULATOR_HOST: localhost:9010
        SPANNER_TEST_PROJECT: test-project
        SPANNER_TEST_INSTANCE: test-instance
