name: nightly-unit-tests

permissions:
  contents: read

on:
  schedule:
    # 05:30 UTC
    - cron:  '30 5 * * *'
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        # Run acceptance tests all supported combinations of Ruby and ActiveRecord.
        ruby: ["3.2", "3.3", "3.4", "4.0"]
        ar: ["~> 7.0.0", "~> 7.1.0", "~> 7.2.0", "~> 8.0.0", "~> 8.1.0"]
        # Exclude combinations that are not supported.
        exclude:
          - ruby: "3.4"
            ar: "~> 7.0.0"
          - ruby: "3.4"
            ar: "~> 7.1.0"
          - ruby: "3.4"
            ar: "~> 7.2.0"
          - ruby: "4.0"
            ar: "~> 7.0.0"
          - ruby: "4.0"
            ar: "~> 7.1.0"
          - ruby: "4.0"
            ar: "~> 7.2.0"
    env:
      AR_VERSION: ${{ matrix.ar }}
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        persist-credentials: false
    - name: Set up Ruby
      uses: ruby/setup-ruby@d45b1a4e94b71acab930e56e79c6aa188764e7f9 # v1.316.0
      with:
        # Disable caching as we are overriding the ActiveRecord below.
        bundler-cache: false
        ruby-version: ${{ matrix.ruby }}
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rake test
