on:
  pull_request:
name: samples
jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        ruby: ["3.1", "3.2", "3.3"]
        ar: ["~> 6.1.0", "~> 7.0.0", "~> 7.1.0", "~> 7.2.0", "~> 8.0.0"]
        # Exclude combinations that are not supported.
        exclude:
          - ruby: "3.1"
            ar: "~> 8.0.0"
    env:
      AR_VERSION: ${{ matrix.ar }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: false
        ruby-version: ${{ matrix.ruby }}
    - name: Install dependencies
      run: bundle install
    - name: Run samples
      run: bundle exec rake all
      working-directory: examples/snippets
